### ISSUE TITLE
rngd --list not showing all sources

### ISSUE THREAD

**Issue by dermotbradley** [nhorman/rng-tools#116]
I have rngd 6.11 built with NIST Beacon and RTLSDR is addition to the usual set.

When I run "rngd --list" the output is:

```
Entropy sources that are available but disabled
1: TPM RNG Device (tpm)
4: NIST Network Entropy Beacon (nist)
Available and enabled entropy sources:
0: Hardware RNG Device (hwrng)
5: JITTER Entropy generator (jitter)
```

However RTLSDR is not mentioned in the output at all. "ldd" confirms that librtlsdr is compiled into the rngd binary.

**Comment by nhorman** [comment]
thats an idiosyncrasy of rngd.  the state of a given entropy source is defined by two pieces of information:
a) If it is enabled or disabled at run time (rtlsdr is 'enabled' if we compile support in at build time, which you have done, meaning that it should appear in the Available and enabled entropy list)

b) If it initializes successfully

My guess is that you don't have a rtlsdr radio connected to your system.  So you've fallen into this odd condition in which rtlsdr is 'enabled' but doesn't initialize properly, due to lack of hardware.  We should probably modify the list output to include entropy sources that are enabled but unavailable.  I can take care of that

**Comment by nhorman** [comment]
fixed in the master branch

**Comment by dermotbradley** [comment]
> My guess is that you don't have a rtlsdr radio connected to your system. So you've fallen into this odd condition in which rtlsdr is 'enabled' but doesn't initialize properly, due to lack of hardware. We should probably modify the list output to include entropy sources that are enabled but unavailable. I can take care of that

Yes, I don't (currently) have a SDR connected. I expected that was what was happening, just thought it was a bit misleading (as the output didn't say "and initialised successfully").

Thanks for the fix and thanks for your responsiveness.
