### ISSUE TITLE
rngd hangs on shutdown

### ISSUE THREAD

**Issue by Stephen-Seo** [nhorman/rng-tools#140]
Lately my system has been hanging on shutdown for 1:30, which indicated some process was timing out before systemd kills it. I booted up my system with `loglevel=7` and without the `quiet` for kernel parameters and took the following screenshot on shutdown.

![Screenshot of shutdown logs](https://seodisparate.com/static/uploads/rngd_shutdown_log_cropped.jpg)
(sorry for the blurriness)

This happens often when I do a `shutdown now` or `sudo shutdown now` from a terminal (Alacritty) in sway (Wayland compositor) as a regular user with sudo privileges, but if I do a fresh login on tty1 and immediately do a `shutdown now`, it usually doesn't have a problem shutting down within a few seconds.

I'm pretty sure rngd is the culprit because if I stop the service before shutting down, then the system has no problems shutting down within a few seconds after invoking `shutdown now`.

EDIT: FYI This is on Arch Linux with AMD processor and GPU, linux-hardened kernel.

EDIT2: `rngd --version` output:

    rngd 6.13
    Copyright 2001-2004 Jeff Garzik
    Copyright 2017 Neil Horman
    Copyright (c) 2001 by Philipp Rumpf
    This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by nhorman** [comment]
I'm afraid none of that tells me anything.  Best thing for you to do would be to modify the rngd unit file so that the ExecStart line has the -d option added to it.  Then attempt to recreate the problem.  When you boot up again, run journalctl on the prior log looking at messages from the rngd unit.  That should provide us with some debug information to understand whats going on.

**Comment by Stephen-Seo** [comment]
Jul 15 22:00:28 ArchCrimson systemd[1]: Reached target Late Shutdown Services.
    Jul 15 22:00:28 ArchCrimson systemd[1]: systemd-poweroff.service: Deactivated successfully.
    Jul 15 22:00:28 ArchCrimson systemd[1]: Finished System Power Off.
    Jul 15 22:00:28 ArchCrimson systemd[1]: Reached target System Power Off.
    Jul 15 22:00:28 ArchCrimson systemd[1]: Shutting down.
    Jul 15 22:00:28 ArchCrimson audit: BPF prog-id=17 op=UNLOAD
    Jul 15 22:00:28 ArchCrimson audit: BPF prog-id=16 op=UNLOAD
    Jul 15 22:00:28 ArchCrimson audit: BPF prog-id=20 op=UNLOAD
    Jul 15 22:00:28 ArchCrimson audit: BPF prog-id=19 op=UNLOAD
    Jul 15 22:00:28 ArchCrimson audit: BPF prog-id=18 op=UNLOAD
    Jul 15 22:00:28 ArchCrimson audit: BPF prog-id=23 op=UNLOAD
    Jul 15 22:00:28 ArchCrimson audit: BPF prog-id=22 op=UNLOAD
    Jul 15 22:00:28 ArchCrimson audit: BPF prog-id=21 op=UNLOAD
    Jul 15 22:00:28 ArchCrimson systemd-shutdown[1]: Syncing filesystems and block devices.
    Jul 15 22:00:28 ArchCrimson systemd-shutdown[1]: Sending SIGTERM to remaining processes...
    Jul 15 22:00:28 ArchCrimson rngd[2349]: [jitter]: DONE Writing to pipe with return 151
    Jul 15 22:00:28 ArchCrimson rngd[2349]: [jitter]: Writing to pipe
    Jul 15 22:00:28 ArchCrimson rngd[2349]: [jitter]: DONE Writing to pipe with return 151
    Jul 15 22:00:28 ArchCrimson rngd[2349]: [jitter]: Writing to pipe
    Jul 15 22:00:28 ArchCrimson rngd[2349]: [jitter]: DONE Writing to pipe with return 151
    Jul 15 22:00:28 ArchCrimson rngd[2349]: [jitter]: Writing to pipe
    Jul 15 22:00:28 ArchCrimson rngd[2349]: [jitter]: DONE Writing to pipe with return 151
    Jul 15 22:00:28 ArchCrimson rngd[2349]: [jitter]: Writing to pipe
    Jul 15 22:00:28 ArchCrimson systemd-journald[400]: Journal stopped

Not sure if this is helpful, I'm going to try to record on my phone output with the kernel parameters set to how I had it before.

**Comment by nhorman** [comment]
Unfortunately, no.  From the above, that looks like a normal shutdown sequence.  I would have expected to see a larger gap between the first and last messages from rngd.  The above looks like it terminates as soon as the SIGTERM is sent.  Normally systemd sends a SIGTERM, followed by a SIGKILL some period later if the process didn't sucessfully stop in response to the SIGTERM.  This to me looks like it worked normally

**Comment by Stephen-Seo** [comment]
I'm going to try what's recommended here https://freedesktop.org/wiki/Software/systemd/Debugging/#index3h2
Hopefully that will provide more information.

**Comment by paulkerry1** [comment]
Hi
I'm also seeing this on Arch with rngd version 6.13 (and have also tested 6.12), on a desktop system with XFCE, and also on Arch systems running tty console only.
It could be caused by the recent systemd updates, currently systemd 249-3
If I create a systemd drop-in /etc/systemd/system/rngd.service.d/override.conf file with

``[Unit]
Conflicts=shutdown.target

then shutdown/reboot works as I would expect.

The same "Conflicts" line is mentioned at...
https://github.com/nhorman/rng-tools/issues/73
https://github.com/systemd/systemd/issues/11821

Regards
Paul.

**Comment by nhorman** [comment]
https://github.com/systemd/systemd/issues/11821#issuecomment-477548703
Based on that it sounds like arch added some default systems setting that are exposing this behavior (though I'm not sure of that), as the logs above still show that rngd is responding to sigterm,  so I'm still not sure what the problem is.  I'd like to see some logs that actually illustrate systems having to send a sigkill to rngd after a long timeout

**Comment by paulkerry1** [comment]
Thanks for the reply. I've investigated and you are correct: it looks purely like an Arch issue with the systemd file.

Using your systemd file from..
https://github.com/nhorman/rng-tools/blob/master/rngd.service
rather than Arch's current systemd file...
https://github.com/archlinux/svntogit-community/blob/packages/rng-tools/trunk/rngd.service

everything works perfectly fine. I'll log a bug on the Arch site and link to this.
Regards
Paul.

**Comment by paulkerry1** [comment]
Thanks for the reply. I've investigated and you are correct: it looks purely like an Arch issue with the systemd file.

Using your systemd file from..
https://github.com/nhorman/rng-tools/blob/master/rngd.service
rather than Arch's current systemd file...
https://github.com/archlinux/svntogit-community/blob/packages/rng-tools/trunk/rngd.service

everything works perfectly fine. I'll log a bug on the Arch site and link to this.
Regards
Paul.
https://bugs.archlinux.org/task/71535

**Comment by paulkerry1** [comment]
This has been fixed in Arch with rng-tools 6.13-2 by a change to the Arch systemd file.
Regards
Paul

**Comment by Stephen-Seo** [comment]
Good to hear a solution was found, closing since it has been resolved.
