### ISSUE TITLE
JITTER_OPT_TIMEOUT default value is too low

### ISSUE THREAD

**Issue by SuperBaobab** [nhorman/rng-tools#198]
Hi,

I upgraded rng-tools from v6.15 to v6.16 and now the rngd service is crashing at startup because of the new 5 seconds jitter init timeout.
The jent_read_entropy time on my system is around 4 to 6 seconds and jitter is the only source of entropy.

For details, my system is on a AWS EC2 t4g.micro instance.
I think 5 seconds is too low for many systems, is it possible to increase the default value ?

Thanks,

**Comment by nhorman** [comment]
Ok, so....set the timeout option on the command line.  It's all in the man page

**Comment by nhorman** [comment]
Well, you're the first that's reported it since we added the option , and I'm not inclined to make it longer just to have someone on another system say it takes too long to timeout.

**Comment by g-v-egidy** [comment]
While testing my changes for force_as_fast_source / --use-slow-sources I also encountered issues with the default JITTER_OPT_TIMEOUT of 5 seconds being too low **sometimes**. On two of my test systems (one being a KVM VM on a modern Epyc server, the other a lower-powered PC-Engines apu4d4 embedded board), jitter did not always initialize. It worked most of the time, but in like 15% of the cases it did time out.

I suggest to increase the time to 10 seconds.

If it is able to provide enough entropy faster, which it will on the majority of systems and program starts, then you don't have to wait longer because of this. The longer timeout will only affect systems where jitter is enabled (probably due to a default config), but always fails to initialize.

I think a 5 second longer timeout for these few systems is a good tradeoff for providing a reliable full-software fallback entropy source.

Also the jitter timeout option is currently not mentioned in the man page. I can provide a patch for one or both, once consensus reached regarding the change of the default timeout.
