### ISSUE TITLE
Some issues with the integration of RDRAND

### ISSUE THREAD

**Issue by joshuaehill** [nhorman/rng-tools#50]
RDRAND isn’t (in most circumstances) an entropy source, per say. It’s an excellent  DRBG with security strength 128, so you should be able to claim a 128-bit computational resistance to attack for the outputs of the call. This isn't really the same thing as "entropy", and in particular, this is a problem for any system trying to create larger keys (say making a 256-bit AES key that you wanted to claim actually had a full 256 bit strength).

This also applies to rngd’s behavior when using RDRAND, as by default the kernel is told that the input RDRAND output should be considered full entropy. (This is surely incorrect, no matter what the underlying attack model is!)

In the case where an attacker can directly query RDRAND any time they choose to, it's not appropriate to claim any _entropy_ (as compared to computational resistance to attack). In the case where the attacker can be denied this access, then the appropriate amount of entropy to credit is on the order of 128 bits per 2^14 bytes. (This is two seed intervals of 128-bit DRBG "generate" calls). This is as a consequence of the [reseed interval](https://software.intel.com/en-us/articles/intel-digital-random-number-generator-drng-software-implementation-guide)).

**Comment by nhorman** [comment]
so....don't use it.

The fact of the matter is, other users on a local system will always have access to the rdrand instruction, as it is unprivileged, or sufficiently so that rngd has no way to know who may be able to access it.  If a user is so concerned with attackers having predictive access to this entropy source, the only practical solution is to turn that source off as an input to rngd (something we already have an option to do)

As for properly crediting the amount of entropy pulled from this source, 128 bits per 2^14 bytes is insanely slow, to the point where the source is effectively useless.  Given that the average users values rngd as a source of sufficiently random data to feed the kernel random pool quickly so as to avoid blocking on /dev/random reads during critical times (like boot), we're not going to default restrict the strength of the source to the value you suggest above.  I would be willing to entertain a patch from you that added an option to opt in to restricting the entropy count to that value when set, but I promise you no one will use it for any practical purpose.

**Comment by joshuaehill** [comment]
Such a behavior would would be useful for any vendor that actually had to explain why the linux RNG was securely seeded to some specific security level. In the abstract, this is required for any product that needed to undergo FIPS 140-2 / CC (to various PPs) / AIS-31 validation.

Even if an attacker doesn't have local access, rngd is still over-crediting the entropy by a multiplicative factor of at least 511.

**Comment by nhorman** [comment]
Several distributions ship rngd exactly as is, and certify with it against FIPS-140-2 / CC, I work for one of them.

If you would like to see it be stronger,  as I noted before, you are welcome to write a patch that allows for an opting into that model, I'm happy to review it.

**Comment by joshuaehill** [comment]
"I don't want /dev/random to block" can be accomplished by just using the RNDADDTOENTCNT ioctl to manually set the kernel's internal kernel entropy estimate (or asking rngd to use /dev/urandom as an input source, which is something that I've actually seen in various folk's "using rngd" instructions!) In order to provide some useful benefit, this tool needs to both introduce additional entropy into the input pool, and not misrepresent the amount of entropy that should be credited.

I'll follow up with a patch.
